//HintName: HostedServiceAttribute.g.cs
// <auto-generated />

namespace Microsoft.Extensions.DependencyInjection.Attributes
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class HostedServiceAttribute : Attribute
    {
    }

    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
    public sealed class HostedServiceAttribute<TService> : Attribute
    {
    }
}