name: BuildingBlocks.ReflectionBenchmark
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup benchmark
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Run benchmark
        run: cd test/BuildingBlocks.ReflectionBenchmark && dotnet build --configuration Release && dotnet run --configuration Release --exporters json --filter '*'