name: BuildingBlocks.ReflectionBenchmark
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup benchmark
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Run benchmark
        run: cd test/BuildingBlocks.ReflectionBenchmark && dotnet run --exporters json --filter '*'

      - name: Store benchmark
        uses: rhysd/github-action-benchmark@v1.20.4
        with:
          name: benchmark
          tool: 'benchmarkdotnet'
          output-file-path: test/BenchmarkDotNet.Artifacts/results/ReflectionBenchmark.Benchmarks-report-full-compressed.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@ktrz'
